version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
      TZ: 'Asia/Shanghai'
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped