version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    command: 
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: test
      TZ: 'Asia/Shanghai'
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped