[project]
name = "fastapi-postgres-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all]>=0.115.12",
    "psycopg2>=2.9.10",
    "sqlmodel>=0.0.24",
    "unicorn[standard]>=2.1.3",
]
